### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by ThaWill** [Alon-L/wumpcraft#3]
![Captura](https://user-images.githubusercontent.com/50968088/60678838-640fbe80-9e4b-11e9-9829-bacca832fd1f.PNG)

I'm doing exactly what it says here and I get this error.

![Captura1](https://user-images.githubusercontent.com/50968088/60678841-670aaf00-9e4b-11e9-97e0-a3a08eeaac1d.PNG)

??????

**Comment by Alon-L** [comment]
Try the next steps:
1. Use the newest commit.
2. Make sure the bot has the "Manage Emojis" permission.
3. Restart the bot and make sure it created the 24 required emojis in your server.

**Comment by DayColor** [comment]
And also give the bot the manage emojis permission.

**Comment by Alon-L** [comment]
No updates.
Create a new report if the issue is still a problem.
