### ISSUE TITLE
Channel permissions

### ISSUE THREAD

**Issue by tocuto** [Alon-L/wumpcraft#4]
When someone creates a channel to play seems like they can't send messages in, but if someone decides to spectate that player they can.
I guess that it'd be better if everyone on the channel could send messages

P.S: I've been checking the bot and the code and it's literally an amazing work! Good job 👏

**Comment by Alon-L** [comment]
Thank you for reporting!
Bug fixed here https://github.com/DayColor/wumpcraft/commit/afac89de62f150bd7e359df36e5f07f5ae1ffe6f
