### ISSUE TITLE
Is it compatible with discord 12?

### ISSUE THREAD

**Issue by ghost** [Alon-L/wumpcraft#9]
My bot is in 12 so I am asking...

**Comment by emdCatalyst** [comment]
It is definitely incompatible with the v12 build of discord.js ,you'll need to run it on v11.

**Comment by ghost** [comment]
V11 is dead now, when will you update it to v12? Or will that not happen?

**Comment by ghost** [comment]
V11 is dead now, when will you update it to v12? Or will that not happen?
